export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';
export const FULL_SCREEN = 'FULL_SCREEN';
export const FULL_SCREEN_EXIT = 'FULL_SCREEN_EXIT';
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';
export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE';

export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOADING = 'USER_LOADING';
export const GET_ERRORS = "GET_ERRORS";
export const GET_SUCCESS = "GET_SUCCESS";
export const GET_COACH_VIEW = "GET_COACH_VIEW";
export const GET_COACH_VIEW2 = "GET_COACH_VIEW2";
export const LOAD_ASSOC_BRANCHES = "LOAD_ASSOC_BRANCHES";
export const TOGGLE_BRANCH = "TOGGLE_BRANCH";
export const LOAD_CHILDS = "LOAD_CHILDS";
export const SELECT_CHILD = "SELECT_CHILD";
export const STUDENT_PROFILE = "STUDENT_PROFILE";
export const SELECT_CHILD_BATCH = "SELECT_CHILD_BATCH";
export const GET_BATCH_DETAILS = "GET_BATCH_DETAILS";
export const GET_FEE_BATCH_DETAILS = "GET_FEE_BATCH_DETAILS";
export const SET_TT = "SET_TT";
export const VIEW_TT = "VIEW_TT";
export const VIEW_BATCH_STUDENTS = "VIEW_BATCH_STUDENTS";
export const SELECT_COACH_BATCH = "SELECT_COACH_BATCH";
export const FETCH_LEAVES = "FETCH_LEAVES";
export const FETCH_LEAVES_ALL = "FETCH_LEAVES_ALL";
export const SET_LEAVES = "SET_LEAVES";
export const APPROVE_LEAVES = "APPROVE_LEAVES";
export const GET_GALLERY = "GET_GALLERY";
export const SUBMIT_FEEDBACK = "SUBMIT_FEEDBACK";
export const VIEW_FEEBACK = "VIEW_FEEBACK";
export const VIEW_PARENT_FEEDBACK = "VIEW_PARENT_FEEDBACK";
export const APPROVE_AND_PUBLISH_FEEDBACK = "APPROVE_AND_PUBLISH_FEEDBACK";


//+++++++++ FENLEY++++++++++//
export const GET_ARTICLE = "GET_ARTICLE";
export const LOAD_STUDENTS = "LOAD_STUDENTS";
export const LOAD_BRANCHES = "LOAD_BRANCHES";
export const LOAD_BATCHES = "LOAD_BATCHES";
export const LOAD_ENQUIRY = "LOAD_ENQUIRY";