export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const USER_LOADED = "USER_LOADED";
export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOG_OUT = "LOG_OUT";
export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";
export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const SELECT_USER_REQUEST = "SELECT_USER_REQUEST";
export const SELECT_USER_SUCCESS = "SELECT_USER_SUCCESS";
export const SELECT_USER_FAIL = "SELECT_USER_FAIL";
export const EDIT_COINS_REQUEST = "EDIT_COINS_REQUEST";
export const EDIT_COINS_SUCCESS = "EDIT_COINS_SUCCESS";
export const EDIT_COINS_FAIL = "EDIT_COINS_FAIL";
export const BLOCK_USER_REQUEST = "BLOCK_USER_REQUEST";
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_FAIL = "BLOCK_USER_FAIL";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const FETCH_CHALLENGE_REQUEST = "FETCH_CHALLENGE_REQUEST";
export const FETCH_CHALLENGE_SUCCESS = "FETCH_CHALLENGE_SUCCESS";
export const FETCH_CHALLENGE_FAIL = "FETCH_CHALLENGE_FAIL";
export const ADD_CHALLENGE_REQUEST = "ADD_CHALLENGE_REQUEST";
export const ADD_CHALLENGE_SUCCESS = "ADD_CHALLENGE_SUCCESS";
export const ADD_CHALLENGE_FAIL = "ADD_CHALLENGE_FAIL";
export const EDIT_CHALLENGE_REQUEST = "EDIT_CHALLENGE_REQUEST";
export const EDIT_CHALLENGE_SUCCESS = "EDIT_CHALLENGE_SUCCESS";
export const EDIT_CHALLENGE_FAIL = "EDIT_CHALLENGE_FAIL";
export const DELETE_CHALLENGE_REQUEST = "DELETE_CHALLENGE_REQUEST";
export const DELETE_CHALLENGE_SUCCESS = "DELETE_CHALLENGE_SUCCESS";
export const DELETE_CHALLENGE_FAIL = "DELETE_CHALLENGE_FAIL";
export const FETCH_CHALLENGETYPE_REQUEST = "FETCH_CHALLENGETYPE_REQUEST";
export const FETCH_CHALLENGETYPE_SUCCESS = "FETCH_CHALLENGETYPE_SUCCESS";
export const FETCH_CHALLENGETYPE_FAIL = "FETCH_CHALLENGETYPE_FAIL";
export const ADD_CHALLENGETYPE_REQUEST = "ADD_CHALLENGETYPE_REQUEST";
export const ADD_CHALLENGETYPE_SUCCESS = "ADD_CHALLENGETYPE_SUCCESS";
export const ADD_CHALLENGETYPE_FAIL = "ADD_CHALLENGETYPE_FAIL";
export const EDIT_CHALLENGETYPE_REQUEST = "EDIT_CHALLENGETYPE_REQUEST";
export const EDIT_CHALLENGETYPE_SUCCESS = "EDIT_CHALLENGETYPE_SUCCESS";
export const EDIT_CHALLENGETYPE_FAIL = "EDIT_CHALLENGETYPE_FAIL";
export const DELETE_CHALLENGETYPE_REQUEST = "DELETE_CHALLENGETYPE_REQUEST";
export const DELETE_CHALLENGETYPE_SUCCESS = "DELETE_CHALLENGETYPE_SUCCESS";
export const DELETE_CHALLENGETYPE_FAIL = "DELETE_CHALLENGETYPE_FAIL";
export const SELECT_CHALLENGETYPE_REQUEST = "SELECT_CHALLENGETYPE_REQUEST";
export const SELECT_CHALLENGETYPE_SUCCESS = "SELECT_CHALLENGETYPE_SUCCESS";
export const SELECT_CHALLENGETYPE_FAIL = "SELECT_CHALLENGETYPE_FAIL";

export const FETCH_CHALLENGECATEGORY_REQUEST =
  "FETCH_CHALLENGECATEGORY_REQUEST";
export const FETCH_CHALLENGECATEGORY_SUCCESS =
  "FETCH_CHALLENGECATEGORY_SUCCESS";
export const FETCH_CHALLENGECATEGORY_FAIL = "FETCH_CHALLENGECATEGORY_FAIL";
export const ADD_CHALLENGECATEGORY_REQUEST = "ADD_CHALLENGECATEGORY_REQUEST";
export const ADD_CHALLENGECATEGORY_SUCCESS = "ADD_CHALLENGECATEGORY_SUCCESS";
export const ADD_CHALLENGECATEGORY_FAIL = "ADD_CHALLENGECATEGORY_FAIL";
export const EDIT_CHALLENGECATEGORY_REQUEST = "EDIT_CHALLENGECATEGORY_REQUEST";
export const EDIT_CHALLENGECATEGORY_SUCCESS = "EDIT_CHALLENGECATEGORY_SUCCESS";
export const EDIT_CHALLENGECATEGORY_FAIL = "EDIT_CHALLENGECATEGORY_FAIL";
export const DELETE_CHALLENGECATEGORY_REQUEST =
  "DELETE_CHALLENGECATEGORY_REQUEST";
export const DELETE_CHALLENGECATEGORY_SUCCESS =
  "DELETE_CHALLENGECATEGORY_SUCCESS";
export const DELETE_CHALLENGECATEGORY_FAIL = "DELETE_CHALLENGECATEGORY_FAIL";
export const SELECT_CHALLENGECATEGORY_REQUEST =
  "SELECT_CHALLENGECATEGORY_REQUEST";
export const SELECT_CHALLENGECATEGORY_SUCCESS =
  "SELECT_CHALLENGECATEGORY_SUCCESS";
export const SELECT_CHALLENGECATEGORY_FAIL = "SELECT_CHALLENGECATEGORY_FAIL";

export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";
